// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Template.Migrations
{
    [DbContext(typeof(IspitDbContext))]
    [Migration("20220909113212_jun2")]
    partial class jun2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Models.Cvece", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("BrPronadjenih")
                        .HasColumnType("int");

                    b.Property<string>("Cvet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("List")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Podrucje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProdavnicaID")
                        .HasColumnType("int");

                    b.Property<string>("Stablo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ProdavnicaID");

                    b.ToTable("CveceUProdavnici");
                });

            modelBuilder.Entity("Models.Pretraga", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Cvet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatumPretrage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("List")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Podrucje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stablo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pretraga");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ProdavnicaeBiljaka");
                });

            modelBuilder.Entity("Models.Cvece", b =>
                {
                    b.HasOne("Models.Prodavnica", null)
                        .WithMany("Cvece")
                        .HasForeignKey("ProdavnicaID");
                });

            modelBuilder.Entity("Models.Prodavnica", b =>
                {
                    b.Navigation("Cvece");
                });
#pragma warning restore 612, 618
        }
    }
}
