// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Template.Migrations
{
    [DbContext(typeof(IspitDbContext))]
    [Migration("20220817112719_Grad2")]
    partial class Grad2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Models.Grad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NazivGrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("X")
                        .HasColumnType("int");

                    b.Property<int>("Y")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Gradovi");
                });

            modelBuilder.Entity("Models.MeteoroloskiPodaci", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("GradoviID")
                        .HasColumnType("int");

                    b.Property<int>("KolicinaPadavina")
                        .HasColumnType("int");

                    b.Property<string>("NazivMeseca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SuncaniDani")
                        .HasColumnType("int");

                    b.Property<int>("Temperatura")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GradoviID");

                    b.ToTable("MeteoroloskiPodaci");
                });

            modelBuilder.Entity("Models.MeteoroloskiPodaci", b =>
                {
                    b.HasOne("Models.Grad", "Gradovi")
                        .WithMany("MeteoroloskiPodataci")
                        .HasForeignKey("GradoviID");

                    b.Navigation("Gradovi");
                });

            modelBuilder.Entity("Models.Grad", b =>
                {
                    b.Navigation("MeteoroloskiPodataci");
                });
#pragma warning restore 612, 618
        }
    }
}
