// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Template.Migrations
{
    [DbContext(typeof(IspitDbContext))]
    partial class IspitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Models.Fabrika", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Fabrika");
                });

            modelBuilder.Entity("Models.Silos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int");

                    b.Property<int?>("MojafabrikaID")
                        .HasColumnType("int");

                    b.Property<string>("Oznaka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrenutnaPopunjenost")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MojafabrikaID");

                    b.ToTable("Silosi");
                });

            modelBuilder.Entity("Models.Silos", b =>
                {
                    b.HasOne("Models.Fabrika", "Mojafabrika")
                        .WithMany("silosi")
                        .HasForeignKey("MojafabrikaID");

                    b.Navigation("Mojafabrika");
                });

            modelBuilder.Entity("Models.Fabrika", b =>
                {
                    b.Navigation("silosi");
                });
#pragma warning restore 612, 618
        }
    }
}
