// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Template.Migrations
{
    [DbContext(typeof(IspitDbContext))]
    partial class IspitDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12");

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Godine")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MecNaKojiUcestvujuID")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("MecNaKojiUcestvujuID");

                    b.ToTable("Igraci");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Datum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PS11")
                        .HasColumnType("int");

                    b.Property<int>("PS12")
                        .HasColumnType("int");

                    b.Property<int>("PS21")
                        .HasColumnType("int");

                    b.Property<int>("PS22")
                        .HasColumnType("int");

                    b.Property<int>("S1")
                        .HasColumnType("int");

                    b.Property<int>("S2")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Mecevi");
                });

            modelBuilder.Entity("Models.Igrac", b =>
                {
                    b.HasOne("Models.Mec", "MecNaKojiUcestvuju")
                        .WithMany("Igraci")
                        .HasForeignKey("MecNaKojiUcestvujuID");

                    b.Navigation("MecNaKojiUcestvuju");
                });

            modelBuilder.Entity("Models.Mec", b =>
                {
                    b.Navigation("Igraci");
                });
#pragma warning restore 612, 618
        }
    }
}
